name: samachar_plus_ott_app
description: A new Flutter project for Samachar Plus OTT App - Multi-platform news and media application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  chewie: ^1.7.4
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  intl: ^0.20.2
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  flutter_localizations:
    sdk: flutter
  # Supabase dependencies
  supabase_flutter: ^1.10.25
  envied: ^0.5.4
  envied_generator: ^0.5.4
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  
  # fonts:
  #   - family: AppIcons
  #     fonts:
  #       - asset: assets/fonts/AppIcons.ttf