name: samachar_plus_ott_app
description: A new Flutter project for Samachar Plus OTT App - Multi-platform news and media application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  http: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  chewie: ^1.7.4
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  flutter_localizations:
    sdk: flutter
  # Supabase dependencies
  supabase_flutter: ^1.10.25
  envied: ^0.5.4
  envied_generator: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf